blog/urls.py
from django.urls import path
from .views import all_posts , post_detail , PostList , PostDetail

app_name = 'blog'

urlpatterns = [
    path('', all_posts),
    path('<int:id>', post_detail,name='postdetail'),

    path('cbv/', PostList.as_view()),
    path('cbv/<int:pk>', PostDetail.as_view()),  # <int:pk>  نستخدم ال  <int:id>  بدل مااسمه
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
    path('settings/', include('settings.urls',namespace='settings')),
    path('summernote/', include('django_summernote.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from .views import about

app_name = 'settings'
urlpatterns = [
    path('',about),

]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='posts/')
    publish_data = models.DateTimeField(default=timezone.now)
    content = models.TextField(max_length=10000000)

    def __str__(self) -> str:
        return self.title

settings/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    blog_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='about')
    subtitle = models.TextField(max_length=10000)
    aboutme = models.TextField(max_length=10000)
    tw_link = models.URLField()
    tk_in_link = models.URLField()
    github_link = models.URLField()

blog/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView , DetailView
# Create your views here.

def all_posts(requent):
    object = Post.objects.all()
    return render(requent,'blog/post_list.html',{'posts':object})


def post_detail(requent,id):
    object = Post.objects.get(id=id)
    return render(requent,'blog/post_detail.html',{'post':object})



class PostList(ListView):
    model = Post
    # template_name = ''
    # context = {}

class PostDetail(DetailView):
    model = Post

settings/views.py
from django.shortcuts import render
from .models import About
# Create your views here.

def about(request):
    object = About.objects.all()
    return render(request,'settings/about.html',{'abouts':object})

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="main-wrapper">

	    <article class="blog-post px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">
			    <header class="blog-post-header">
				    <h2 class="title mb-2">{{post.title}}</h2>
				    <div class="meta mb-3">
						<span class="date">Published 2 days ago</span>
						<span class="time">5 min read</span><span class="comment">
							<a  class="text-link" href="#">4 comments</a>
						</span>
					</div>
			    </header>

			    <div class="blog-post-body">
				    <figure class="blog-banner">
				        <a href="https://made4dev.com">
							<img class="img-fluid" src="{{post.image.url}}" alt="image"></a>
				        <figcaption class="mt-2 text-center image-caption">Image Credit:
							<a class="theme-link" href="#" target="_blank">made4dev.com (Premium Programming T-shirts)</a></figcaption>
				    </figure>
				    <p>
						{{post.content|safe}}
					</p>
			    </div>


				<nav class="blog-nav nav nav-justified my-5">
				  <a class="nav-link-prev nav-item nav-link rounded-left" href="/blog/">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
				  <a class="nav-link-next nav-item nav-link rounded-right" href="/blog/2">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
				</nav>

				<div class="blog-comments-section">
					<div id="disqus_thread"></div>
					<script>
					    /**
					     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT
					     *  THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR
					     *  PLATFORM OR CMS.
					     *
					     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT:
					     *  https://disqus.com/admin/universalcode/#configuration-variables
					     */
					    /*
					    var disqus_config = function () {
					        // Replace PAGE_URL with your page's canonical URL variable
					        this.page.url = PAGE_URL;

					        // Replace PAGE_IDENTIFIER with your page's unique identifier variable
					        this.page.identifier = PAGE_IDENTIFIER;
					    };
					    */

					    (function() {  // REQUIRED CONFIGURATION VARIABLE: EDIT THE SHORTNAME BELOW
					        var d = document, s = d.createElement('script');

					        // IMPORTANT TODO: Replace 3wmthemes with your forum shortname!
					        s.src = 'https://3wmthemes.disqus.com/embed.js';

					        s.setAttribute('data-timestamp', +new Date());
					        (d.head || d.body).appendChild(s);
					    })();
					</script>
					<noscript>
					    Please enable JavaScript to view the
					    <a href="https://disqus.com/?ref_noscript" rel="nofollow">
					        comments powered by Disqus.
					    </a>
					</noscript>
				</div><!--//blog-comments-section-->

		    </div><!--//container-->
	    </article>

	    <section class="promo-section theme-bg-light py-5 text-center">
		    <div class="container">
			    <h2 class="title">Promo Section Heading</h2>
			    <p>You can use this section to promote your side projects etc. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. </p>
                <figure class="promo-figure">
			        <a href="https://made4dev.com" target="_blank"><img class="img-fluid" src=" {% static 'assets/images/promo-banner.jpg' %}" alt="image"></a>
			    </figure>
		    </div><!--//container-->
	    </section><!--//promo-section-->

	    <footer class="footer text-center py-2 theme-bg-dark">

	        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="https://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>

	    </footer>

    </div><!--//main-wrapper-->
	{% endblock body %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block body %}
 	<div class="main-wrapper">
	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center single-col-max-width">
			    <h2 class="heading">DevBlog - A Blog Template Made For Developers</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center">
	                    <div class="col-12 col-md-9">
	                        <label class="sr-only" for="semail">Your email</label>
	                        <input type="email" id="semail" name="semail1" class="form-control me-md-1 semail" placeholder="Enter email">
	                    </div>
	                    <div class="col-12 col-md-2">
	                        <button type="submit" class="btn btn-primary">Subscribe</button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
		    </div><!--//container-->
	    </section>


	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">
				{% for post  in posts %}
				<div class="item mb-5">
				    <div class="row g-3 g-xl-0">
					    <div class="col-2 col-xl-3">
					        <img class="img-fluid post-thumb " src="{{post.image.url}}" alt="image">
					    </div>
					    <div class="col">
						    <h3 class="title mb-1">
								<a class="text-link" href="{% url 'blog:postdetail' post.id %}">{{post}}</a>
							</h3>
						    <div class="meta mb-1"><span class="date">{{post.publish_data}}</span>
								<span class="time">5 min read</span>
								<span class="comment">
									<a class="text-link" href="#">8 comments</a>
								</span>
							</div>
						    <div class="intro">{{post.content|safe|truncatewords:40}}</div>
						    <a class="text-link" href="{% url 'blog:postdetail' post.id %} ">Read more &rarr;</a>
					    </div><!--//col-->
				    </div><!--//row-->
			    </div><!--//item-->
				{% endfor %}



			    <nav class="blog-nav nav nav-justified my-5">
				  <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="/blog/">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
				  <a class="nav-link-next nav-item nav-link rounded" href="/blog/1">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
				</nav>

		    </div>
	    </section>
	</div>
{% endblock body %}

settings/templates/settings/about.html
{% extends 'base.html' %}
{% block body %}
    <div class="main-wrapper">
	    <article class="about-section py-5">
		    <div class="container">
				{% for about in abouts %}
			    <h2 class="title mb-3">About Me</h2>

			    <figure><img class="img-fluid rounded-circle float-end" src={{about.image.url}} alt="image"></figure>
			    <p>{{about.subtitle|safe}}</p>


				{% endfor %}
			</div>
	    </article><!--//about-section-->

	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center">
				{% for about in abouts %}
			    <h2 class="heading">Newsletter</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center">
	                    <div class="col-12 col-md-9">
	                        <label class="sr-only" for="semail">Your email</label>
	                        <input type="email" id="semail" name="semail1" class="form-control me-md-1 semail" placeholder="Enter email">
	                    </div>
	                    <div class="col-12 col-md-2">
	                        <button type="submit" class="btn btn-primary">Subscribe</button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
				{% endfor %}
			</div><!--//container-->
	    </section>

	    <footer class="footer text-center py-2 theme-bg-dark">

	        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="#" target="_blank">Xiaoying Riley</a> for developers</small>

	    </footer>

    </div><!--//main-wrapper-->
	{% endblock body %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>DevBlog Developers</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="{% static 'assets/images/blog.jpg' %} ">

    <!-- FontAwesome JS-->
	<script defer src=" {% static 'assets/fontawesome/js/all.min.js' %} "></script>

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-1.css' %}">

</head>

<body>

    <header class="header text-center">
	    <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="index.html">Anthony's Blog</a></h1>

	    <nav class="navbar navbar-expand-lg navbar-dark" >

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src=" {% static 'assets/images/blog/blog-post-thumb-2.jpg' %} " alt="image" >

					<div class="bio mb-3">Hi, my name is mod . Briefly introduce yourself here. You can also provide a link to the about page.<br>
						<a href="/settings/">Find out more about me</a>
					</div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
			        </ul><!--//social-list-->
			        <hr>
				</div><!--//profile-section-->

				<ul class="navbar-nav flex-column text-start">
					<li class="nav-item">
					    <a class="nav-link active" href="/blog/"><i class="fas fa-home fa-fw me-2"></i>Blog Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="/blog/"><i class="fas fa-bookmark fa-fw me-2"></i>Blog Post</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="/settings/"><i class="fas fa-user fa-fw me-2"></i>About Me</a>
					</li>
				</ul>

				<div class="my-2 my-md-3">
				    <a class="btn btn-primary" href="/blog/" target="_self">Get in Touch</a>
				</div>
			</div>
		</nav>
    </header>

    {% block body %}

    {% endblock body %}


    <!-- Javascript -->
    <script src="{% static 'assets/plugins/popper.min.js' %} "></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>



</body>
</html>